export type Market = 'used' | 'new';
export type Car = {
  id: number; market: Market; brand: string; model: string; trim: string; year: number;
  price: number; oldPrice?: number; mileage: number; engine: number; power: number;
  fuel: string; gearbox: string; drive: string; body: string; location: string;
  score: number; fit: number; confidence: number; image: string; source: string;
  consumption: string; annualCost: string; firstYear: string; risk: string;
  highlights: string[]; flags: string[]; questions: string[];
};

export const cars: Car[] = [
  { id: 1, market: 'used', brand: 'Škoda', model: 'Octavia', trim: '1.5 TSI Style', year: 2020, price: 67900, oldPrice: 70900, mileage: 78300, engine: 1498, power: 150, fuel: 'Benzyna', gearbox: 'Automatyczna', drive: 'FWD', body: 'Kombi', location: 'Warszawa', score: 84, fit: 92, confidence: 88, source: 'OTOMOTO', consumption: '6,2–7,4 l', annualCost: '9 200–11 800 zł', firstYear: '12 400–17 900 zł', risk: 'Niskie', highlights: ['Pełna historia ASO', 'Cena 4% poniżej rynku', 'Bogate wyposażenie'], flags: ['Sprawdź pracę skrzyni DSG'], questions: ['Czy olej w DSG był wymieniany?', 'Czy auto miało naprawy lakiernicze?', 'Czy jest komplet faktur z serwisu?'], image: 'https://images.unsplash.com/photo-1549317661-bd32c8ce0db2?auto=format&fit=crop&w=1200&q=85' },
  { id: 2, market: 'used', brand: 'Audi', model: 'A4', trim: '2.0 TDI quattro', year: 2018, price: 79900, mileage: 142500, engine: 1968, power: 190, fuel: 'Diesel', gearbox: 'Automatyczna', drive: 'AWD', body: 'Kombi', location: 'Poznań', score: 67, fit: 86, confidence: 72, source: 'OLX', consumption: '5,8–7,1 l', annualCost: '12 800–17 500 zł', firstYear: '18 000–27 000 zł', risk: 'Średnie', highlights: ['Napęd quattro', 'Dobra konfiguracja', 'Polski salon'], flags: ['Wysoki przebieg', 'Brak faktury za rozrząd', 'Możliwy serwis S tronic'], questions: ['Kiedy wymieniono rozrząd?', 'Czy serwisowano skrzynię co 60 tys. km?', 'Dlaczego auto jest sprzedawane?'], image: 'https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6?auto=format&fit=crop&w=1200&q=85' },
  { id: 3, market: 'used', brand: 'BMW', model: 'Seria 3', trim: '320i xDrive', year: 2019, price: 96900, oldPrice: 99900, mileage: 91000, engine: 1998, power: 184, fuel: 'Benzyna', gearbox: 'Automatyczna', drive: 'AWD', body: 'Sedan', location: 'Kraków', score: 78, fit: 95, confidence: 82, source: 'OTOMOTO', consumption: '7,3–8,8 l', annualCost: '13 500–17 200 zł', firstYear: '17 500–24 000 zł', risk: 'Niskie', highlights: ['Bardzo dobre dopasowanie', 'Udokumentowany serwis', 'Napęd xDrive'], flags: ['Dwa elementy lakierowane'], questions: ['Które elementy były lakierowane i dlaczego?', 'Czy wykonano serwis xDrive?', 'Czy można wykonać pomiar lakieru?'], image: 'https://images.unsplash.com/photo-1555215695-3004980ad54e?auto=format&fit=crop&w=1200&q=85' },
  { id: 4, market: 'used', brand: 'Toyota', model: 'Corolla', trim: '1.8 Hybrid Comfort', year: 2021, price: 82900, mileage: 61200, engine: 1798, power: 122, fuel: 'Hybryda', gearbox: 'Automatyczna', drive: 'FWD', body: 'Hatchback', location: 'Gdańsk', score: 89, fit: 79, confidence: 94, source: 'AutoScout24', consumption: '4,5–5,4 l', annualCost: '7 400–9 800 zł', firstYear: '9 800–13 500 zł', risk: 'Bardzo niskie', highlights: ['Gwarancja Relax', 'Niskie koszty', 'Wzorowa historia'], flags: ['Mniejszy bagażnik'], questions: ['Czy wykonano test baterii hybrydowej?', 'Czy gwarancja Relax jest aktywna?', 'Czy auto ma drugi komplet kół?'], image: 'https://images.unsplash.com/photo-1623869675781-80aa31012a5a?auto=format&fit=crop&w=1200&q=85' },
  { id: 5, market: 'used', brand: 'Volkswagen', model: 'Passat', trim: '2.0 TDI Business', year: 2017, price: 59900, mileage: 197000, engine: 1968, power: 150, fuel: 'Diesel', gearbox: 'Automatyczna', drive: 'FWD', body: 'Kombi', location: 'Wrocław', score: 48, fit: 74, confidence: 65, source: 'OLX', consumption: '5,7–6,9 l', annualCost: '14 000–20 000 zł', firstYear: '21 000–33 000 zł', risk: 'Wysokie', highlights: ['Dużo miejsca', 'Dobre spalanie'], flags: ['Niepełna historia', 'Podejrzanie niska cena', 'DPF i DSG do weryfikacji'], questions: ['Czy sprzedający udostępni VIN?', 'Kiedy serwisowano DSG?', 'Czy DPF był wymieniany lub czyszczony?'], image: 'https://images.unsplash.com/photo-1619767886558-efdc259cde1a?auto=format&fit=crop&w=1200&q=85' },
  { id: 6, market: 'new', brand: 'Kia', model: 'Sportage', trim: '1.6 T-GDI M DCT', year: 2026, price: 139900, oldPrice: 146900, mileage: 5, engine: 1598, power: 160, fuel: 'Benzyna', gearbox: 'Automatyczna', drive: 'FWD', body: 'SUV', location: 'Katowice', score: 87, fit: 83, confidence: 96, source: 'Dealer Kia', consumption: '7,1–8,4 l', annualCost: '11 500–14 800 zł', firstYear: '13 000–16 500 zł', risk: 'Gwarancja 7 lat', highlights: ['Rabat 7 000 zł', '7 lat gwarancji', 'Dostępny od ręki'], flags: ['Wyższa utrata wartości'], questions: ['Czy rabat łączy się z finansowaniem?', 'Jaki jest termin odbioru?', 'Czy pakiet serwisowy jest w cenie?'], image: 'https://images.unsplash.com/photo-1619767886558-efdc259cde1a?auto=format&fit=crop&w=1200&q=85' },
  { id: 7, market: 'new', brand: 'Toyota', model: 'C-HR', trim: '1.8 Hybrid Comfort', year: 2026, price: 128900, mileage: 0, engine: 1798, power: 140, fuel: 'Hybryda', gearbox: 'Automatyczna', drive: 'FWD', body: 'SUV', location: 'Łódź', score: 91, fit: 80, confidence: 97, source: 'Dealer Toyota', consumption: '4,7–5,3 l', annualCost: '8 600–10 700 zł', firstYear: '10 000–12 500 zł', risk: 'Gwarancja 3 lata', highlights: ['Niskie spalanie', 'Wysoka wartość rezydualna', 'Dobra cena'], flags: ['Ograniczona przestrzeń z tyłu'], questions: ['Czy cena obejmuje lakier?', 'Ile kosztuje gwarancja przedłużona?', 'Czy auto jest z roku modelowego 2026?'], image: 'https://images.unsplash.com/photo-1590362891991-f776e747a588?auto=format&fit=crop&w=1200&q=85' },
];

export const money = (value: number) => new Intl.NumberFormat('pl-PL').format(value) + ' zł';
